interface Words {
  [key: string]: {
    word: string;
    translation: string;
    original: string;
    category: string;
  }[];
}

const words: Words = {
  english: [
    {
      word: "chair",
      translation: "krzesło",
      original: "chair",
      category: "Meble",
    },
    {
      word: "computer",
      translation: "komputer",
      original: "computer",
      category: "Technologia",
    },
    {
      word: "guitar",
      translation: "gitara",
      original: "guitar",
      category: "Muzyka",
    },
    {
      word: "television",
      translation: "telewizja",
      original: "television",
      category: "Elektronika",
    },
    {
      word: "book",
      translation: "książka",
      original: "book",
      category: "Literatura",
    },
    {
      word: "pencil",
      translation: "ołówek",
      original: "pencil",
      category: "Przybory szkolne",
    },
    {
      word: "shoe",
      translation: "but",
      original: "shoe",
      category: "Ciuchy",
    },
    {
      word: "coffee",
      translation: "kawa",
      original: "coffee",
      category: "Napój",
    },
    {
      word: "pizza",
      translation: "pizza",
      original: "pizza",
      category: "Jedzenie",
    },
    {
      word: "house",
      translation: "dom",
      original: "house",
      category: "budynek",
    },
    {
      word: "ocean",
      translation: "ocean",
      original: "ocean",
      category: "Geografia",
    },
    {
      word: "violin",
      translation: "skrzypce",
      original: "violin",
      category: "Muzyka",
    },
    {
      word: "airplane",
      translation: "samolot",
      original: "airplane",
      category: "Pojazd",
    },
    {
      word: "chocolate",
      translation: "czekolada",
      original: "chocolate",
      category: "Jedzenie",
    },
    {
      word: "camera",
      translation: "kamera",
      original: "camera",
      category: "Przedmiot",
    },
    {
      word: "telephone",
      translation: "telefon",
      original: "telephone",
      category: "Elektronika",
    },
    {
      word: "umbrella",
      translation: "parasol",
      original: "umbrella",
      category: "Przedmiot",
    },
    {
      word: "soccer",
      translation: "piłka nożna",
      original: "soccer",
      category: "Sport",
    },
    {
      word: "mirror",
      translation: "lustro",
      original: "mirror",
      category: "Meble",
    },
    {
      word: "diamond",
      translation: "diament",
      original: "diamond",
      category: "Biżuteria",
    },
    {
      word: "toilet",
      translation: "toaleta",
      original: "toilet",
      category: "dom",
    },
    {
      word: "sweater",
      translation: "sweter",
      original: "sweater",
      category: "ciuchy",
    },
    {
      word: "skyscraper",
      translation: "drapacz chmur",
      original: "skyscraper",
      category: "budynek",
    },
    {
      word: "waterfall",
      translation: "wodospad",
      original: "waterfall",
      category: "natura",
    },
    {
      word: "banana",
      translation: "banan",
      original: "banana",
      category: "jedzenie",
    },
    {
      word: "piano",
      translation: "pianino",
      original: "piano",
      category: "Muzyka",
    },
    {
      word: "fireplace",
      translation: "kominek",
      original: "fireplace",
      category: "Dom",
    },
    {
      word: "jacket",
      translation: "kurtka",
      original: "jacket",
      category: "Ciuchy",
    },
    {
      word: "pepper",
      translation: "pepper",
      original: "pepper",
      category: "Jedzenie",
    },
    {
      word: "skateboard",
      translation: "deskorolka",
      original: "skateboard",
      category: "Przedmiot",
    },
    {
      word: "elephant",
      translation: "słoń",
      original: "elephant",
      category: "Zwierzęta",
    },
    {
      word: "laptop",
      translation: "laptop",
      original: "laptop",
      category: "Przedmiot",
    },
    {
      word: "gymnastics",
      translation: "gimnastyka",
      original: "gymnastics",
      category: "Sport",
    },
    {
      word: "cactus",
      translation: "kaktus",
      original: "cactus",
      category: "Natura",
    },
    {
      word: "magazine",
      translation: "czasopismo",
      original: "magazine",
      category: "Literatura",
    },
    {
      word: "snowflake",
      translation: "płatek śniegu",
      original: "snowflake",
      category: "natura",
    },
    {
      word: "giraffe",
      translation: "żyrafa",
      original: "giraffe",
      category: "Zwierzęta",
    },
    {
      word: "motorcycle",
      translation: "motocykl",
      original: "motorcycle",
      category: "Pojazd",
    },
    {
      word: "towel",
      translation: "ręcznik",
      original: "towel",
      category: "Przedmiot",
    },
    {
      word: "sunglasses",
      translation: "okulary słoneczne",
      original: "sunglasses",
      category: "Przedmiot",
    },
    { word: "yoga", translation: "yoga", original: "yoga", category: "sport" },
    {
      word: "penguin",
      translation: "pingwin",
      original: "penguin",
      category: "Zwierzęta",
    },
    {
      word: "popcorn",
      translation: "popcorn",
      original: "popcorn",
      category: "Jedzenie",
    },
    {
      word: "mountain",
      translation: "góra",
      original: "mountain",
      category: "Geografia",
    },
    {
      word: "basketball",
      translation: "koszykówka",
      original: "basketball",
      category: "Sport",
    },
    {
      word: "butterfly",
      translation: "motyl",
      original: "butterfly",
      category: "Zwierzęta",
    },
    {
      word: "suitcase",
      translation: "walizka",
      original: "suitcase",
      category: "Podróż",
    },
    {
      word: "watermelon",
      translation: "arbuz",
      original: "watermelon",
      category: "Jedzenie",
    },
    {
      word: "candle",
      translation: "świeczka",
      original: "candle",
      category: "Przedmiot",
    },
  ],
  spanish: [
    {
      word: "sillon",
      translation: "fotel",
      original: "sillón",
      category: "Furniture",
    },
    {
      word: "naranja",
      translation: "pomarańcza",
      original: "naranja",
      category: "Jedzenie",
    },
    {
      word: "manzana",
      translation: "jabłko",
      original: "manzana",
      category: "Jedzenie",
    },
    {
      word: "guitarra",
      translation: "gitara",
      original: "guitarra",
      category: "Muzyka",
    },
    {
      word: "telefono",
      translation: "telefon",
      original: "teléfono",
      category: "Przedmiot",
    },
    {
      word: "mapa",
      translation: "mapa",
      original: "mapa",
      category: "Przedmiot",
    },
    {
      word: "bicicleta",
      translation: "rower",
      original: "bicicleta",
      category: "Pojazd",
    },
    {
      word: "televisor",
      translation: "telewizja",
      original: "televisor",
      category: "Przedmiot",
    },
    {
      word: "musica",
      translation: "muzyka",
      original: "música",
      category: "Muzyka",
    },
    {
      word: "plato",
      translation: "talerz",
      original: "plato",
      category: "Jedzenie",
    },
    {
      word: "hotel",
      translation: "hotel",
      original: "hotel",
      category: "Budynek",
    },
    {
      word: "delfin",
      translation: "delfin",
      original: "delfín",
      category: "Zwierzęta",
    },
    {
      word: "gato",
      translation: "kot",
      original: "gato",
      category: "Zwierzęta",
    },
    {
      word: "restaurante",
      translation: "restauracja",
      original: "restaurante",
      category: "Jedzenie",
    },
    {
      word: "internet",
      translation: "internet",
      original: "internet",
      category: "Przedmiot",
    },
    {
      word: "chocolate",
      translation: "czekolada",
      original: "chocolate",
      category: "Jedzenie",
    },
    {
      word: "silla",
      translation: "krzesło",
      original: "silla",
      category: "Meble",
    },
    {
      word: "avion",
      translation: "samolot",
      original: "avión",
      category: "Pojazd",
    },
    {
      word: "teclado",
      translation: "klawiatura",
      original: "teclado",
      category: "Przedmiot",
    },
    {
      word: "tomate",
      translation: "pomidor",
      original: "tomate",
      category: "Jedzenie",
    },
    {
      word: "camara",
      translation: "kamera",
      original: "cámara",
      category: "Przedmiot",
    },
    {
      word: "juego",
      translation: "gra",
      original: "juego",
      category: "Rozrywka",
    },
    {
      word: "reloj",
      translation: "zegarek",
      original: "reloj",
      category: "Przedmiot",
    },
    {
      word: "teatro",
      translation: "teatr",
      original: "teatro",
      category: "Budynek",
    },
    {
      word: "maleta",
      translation: "walizka",
      original: "maleta",
      category: "Przedmiot",
    },
    {
      word: "botella",
      translation: "butelka",
      original: "botella",
      category: "Przedmiot",
    },
    {
      word: "piano",
      translation: "pianino",
      original: "piano",
      category: "Muzyka",
    },
    {
      word: "videojuego",
      translation: "gra komputerowa",
      original: "videojuego",
      category: "Rozrywka",
    },
    {
      word: "mesa",
      translation: "stół",
      original: "mesa",
      category: "Meble",
    },
    {
      word: "paraguas",
      translation: "parasol",
      original: "paraguas",
      category: "Przedmiot",
    },
    {
      word: "estacionamiento",
      translation: "parking",
      original: "estacionamiento",
      category: "miejsce",
    },
    {
      word: "lapiz",
      translation: "ołówek",
      original: "lápiz",
      category: "przybory szkolne",
    },
    {
      word: "basura",
      translation: "śmieci",
      original: "basura",
      category: "Przedmiot",
    },
    {
      word: "ropa",
      translation: "ciuchy",
      original: "ropa",
      category: "Ciuchy",
    },
    {
      word: "ciudad",
      translation: "miasto",
      original: "ciudad",
      category: "miejsca",
    },
    {
      word: "cancion",
      translation: "piosenka",
      original: "canción",
      category: "rozrywka",
    },
    {
      word: "adios",
      translation: "do widzenia",
      original: "adiós",
      category: "Powitanie",
    },
    {
      word: "aguila",
      translation: "orzeł",
      original: "águila",
      category: "Zwierzęta",
    },
    {
      word: "amigo",
      translation: "przyjaciel",
      original: "amigo",
      category: "ludzie",
    },
    {
      word: "bano",
      translation: "łazienka",
      original: "baño",
      category: "Dom",
    },
    {
      word: "bravo",
      translation: "odwaga",
      original: "bravo",
      category: "emocje",
    },
    {
      word: "casa",
      translation: "dom",
      original: "casa",
      category: "miejsca",
    },
    {
      word: "cerveza",
      translation: "piwo",
      original: "cerveza",
      category: "jedzenie",
    },
    { word: "dia", translation: "dzień", original: "día", category: "czas" },
    {
      word: "elegante",
      translation: "elegancki",
      original: "elegante",
      category: "Wygląd",
    },
    {
      word: "familia",
      translation: "rodzina",
      original: "familia",
      category: "ludzie",
    },
    {
      word: "guitarra",
      translation: "gitara",
      original: "guitarra",
      category: "Muzyka",
    },
    {
      word: "hola",
      translation: "cześć",
      original: "hola",
      category: "Powitanie",
    },
    {
      word: "iglesia",
      translation: "kościół",
      original: "iglesia",
      category: "Budynek",
    },
    {
      word: "jamon",
      translation: "szynka",
      original: "jamón",
      category: "Jedzenie",
    },
    {
      word: "jardin",
      translation: "ogród",
      original: "jardín",
      category: "Miejsce",
    },
    {
      word: "kiwi",
      translation: "kiwi",
      original: "kiwi",
      category: "Jedzenie",
    },
    {
      word: "lapiz",
      translation: "ołówek",
      original: "lápiz",
      category: "Przybory szkolne",
    },
    {
      word: "manana",
      translation: "jutro",
      original: "mañana",
      category: "czas",
    },
    {
      word: "nacion",
      translation: "naród",
      original: "nación",
      category: "polityka",
    },
    {
      word: "nono",
      translation: "płaczliwy",
      original: "ñoño",
      category: "emocje",
    },
    {
      word: "oido",
      translation: "ucho",
      original: "oído",
      category: "człowiek",
    },
    {
      word: "queso",
      translation: "ser",
      original: "queso",
      category: "jedzenie",
    },
    {
      word: "rosa",
      translation: "rose",
      original: "rosa",
      category: "natura",
    },
    {
      word: "silla",
      translation: "krzesło",
      original: "silla",
      category: "meble",
    },
    {
      word: "taco",
      translation: "taco",
      original: "taco",
      category: "jedzenie",
    },
    {
      word: "uva",
      translation: "winogron",
      original: "uva",
      category: "jedzenie",
    },
    {
      word: "vacaciones",
      translation: "wakacje",
      original: "vacaciones",
      category: "podróż",
    },
    {
      word: "yoga",
      translation: "yoga",
      original: "yoga",
      category: "ćwiczenia",
    },
    {
      word: "zapato",
      translation: "but",
      original: "zapato",
      category: "ciuchy",
    },
    {
      word: "arbol",
      translation: "drzewo",
      original: "árbol",
      category: "rosliny",
    },
    {
      word: "exito",
      translation: "sukces",
      original: "éxito",
      category: "motywacja",
    },
  ],
  polish: [
    {
      word: "samolot",
      translation: "samolot",
      original: "samolot",
      category: "pojazd",
    },
    {
      word: "milosc",
      translation: "miłość",
      original: "miłość",
      category: "emocje",
    },
    {
      word: "zolw",
      translation: "zolw",
      original: "żółw",
      category: "zwierzęta",
    },
    {
      word: "kot",
      translation: "kot",
      original: "kot",
      category: "zwierzęta",
    },
    {
      word: "pies",
      translation: "pies",
      original: "pies",
      category: "zwierzęta",
    },
    {
      word: "ksiazka",
      translation: "ksiazka",
      original: "książka",
      category: "przedmiot",
    },
    {
      word: "witaj",
      translation: "witaj",
      original: "witaj",
      category: "powitanie",
    },
    {
      word: "do widzenia",
      translation: "do widzenia",
      original: "do widzenia",
      category: "powitanie",
    },
    {
      word: "dom",
      translation: "dom",
      original: "dom",
      category: "budynek",
    },
    {
      word: "gra",
      translation: "gra",
      original: "gra",
      category: "rozrywka",
    },
    {
      word: "jedzenie",
      translation: "jedzenie",
      original: "jedzenie",
      category: "jedzenie",
    },
    {
      word: "woda",
      translation: "woda",
      original: "woda",
      category: "napój",
    },
    {
      word: "szkoda",
      translation: "szkoda",
      original: "szkoda",
      category: "emocje",
    },
    {
      word: "kawa",
      translation: "kawa",
      original: "kawa",
      category: "napój",
    },
    {
      word: "herbata",
      translation: "herbata",
      original: "herbata",
      category: "napój",
    },
    {
      word: "babcia",
      translation: "babcia",
      original: "babcia",
      category: "rodzina",
    },
    {
      word: "czekolada",
      translation: "czekolada",
      original: "czekolada",
      category: "jedzenie",
    },
    {
      word: "domek",
      translation: "domek",
      original: "domek",
      category: "budynek",
    },
    {
      word: "ekran",
      translation: "ekran",
      original: "ekran",
      category: "przedmiot",
    },
    {
      word: "filizanka",
      translation: "filizanka",
      original: "filiżanka",
      category: "przedmiot",
    },
    {
      word: "grzyb",
      translation: "grzyb",
      original: "grzyb",
      category: "jedzenie",
    },
    {
      word: "hazard",
      translation: "hazard",
      original: "hazard",
      category: "rozrywka",
    },
    {
      word: "igla",
      translation: "igla",
      original: "igła",
      category: "przedmiot",
    },
    {
      word: "jablko",
      translation: "jablko",
      original: "jabłko",
      category: "jedzenie",
    },
    {
      word: "kawa",
      translation: "kawa",
      original: "kawa",
      category: "napój",
    },
    {
      word: "lampa",
      translation: "lampa",
      original: "lampa",
      category: "przedmiot",
    },
    {
      word: "marchew",
      translation: "marchew",
      original: "marchew",
      category: "jedzenie",
    },
    {
      word: "niedziela",
      translation: "niedziela",
      original: "niedziela",
      category: "czas",
    },
    {
      word: "obraz",
      translation: "obraz",
      original: "obraz",
      category: "przedmiot",
    },
    {
      word: "pajak",
      translation: "pajak",
      original: "pająk",
      category: "zwierzęta",
    },
    {
      word: "reka",
      translation: "reka",
      original: "ręka",
      category: "człowiek",
    },
    {
      word: "serce",
      translation: "serce",
      original: "serce",
      category: "człowiek",
    },
    {
      word: "torebka",
      translation: "torebka",
      original: "torebka",
      category: "przedmiot",
    },
    {
      word: "ucho",
      translation: "ucho",
      original: "ucho",
      category: "człowiek",
    },
    { word: "woda", translation: "woda", original: "woda", category: "napój" },
    {
      word: "yacht",
      translation: "yacht",
      original: "jacht",
      category: "pojazd",
    },
    {
      word: "zamek",
      translation: "zamek",
      original: "zamek",
      category: "budynek",
    },
  ],
  french: [
    {
      word: "bonjour",
      translation: "witaj",
      original: "bonjour",
      category: "powitanie",
    },
    {
      word: "chateau",
      translation: "zamek",
      original: "château",
      category: "budynek",
    },
    {
      word: "delicieux",
      translation: "przyszne",
      original: "délicieux",
      category: "jedzenie",
    },
    {
      word: "ecole",
      translation: "szkola",
      original: "école",
      category: "edukacja",
    },
    {
      word: "fleur",
      translation: "kwiatek",
      original: "fleur",
      category: "natura",
    },
    {
      word: "gateau",
      translation: "ciasto",
      original: "gâteau",
      category: "jedzenie",
    },
    {
      word: "heureux",
      translation: "szczescie",
      original: "heureux",
      category: "emocje",
    },
    {
      word: "invitation",
      translation: "zaproszenie",
      original: "invitation",
      category: "wydarzenia",
    },
    {
      word: "jardin",
      translation: "ogród",
      original: "jardin",
      category: "natura",
    },
    {
      word: "kiwi",
      translation: "kiwi",
      original: "kiwi",
      category: "jedzenie",
    },
    {
      word: "lingerie",
      translation: "bielizna",
      original: "lingerie",
      category: "ciuchy",
    },
    {
      word: "musique",
      translation: "muzyka",
      original: "musique",
      category: "rozrywka",
    },
    {
      word: "noir",
      translation: "czarny",
      original: "noir",
      category: "kolor",
    },
    {
      word: "oiseau",
      translation: "ptak",
      original: "oiseau",
      category: "zwierzęta",
    },
    {
      word: "parfum",
      translation: "perfumy",
      original: "parfum",
      category: "uroda",
    },
    {
      word: "quatre",
      translation: "cztery",
      original: "quatre",
      category: "liczby",
    },
    {
      word: "restaurant",
      translation: "restauracja",
      original: "restaurant",
      category: "budynek",
    },
    {
      word: "sourire",
      translation: "usmiech",
      original: "sourire",
      category: "emocje",
    },
    {
      word: "tableau",
      translation: "obraz",
      original: "tableau",
      category: "sztuka",
    },
    {
      word: "unique",
      translation: "wyjatkowy",
      original: "unique",
      category: "cechy",
    },
    {
      word: "vache",
      translation: "krowa",
      original: "vache",
      category: "zwierzęta",
    },
    {
      word: "wagon",
      translation: "wóz",
      original: "wagon",
      category: "pojazdy",
    },
    {
      word: "yoga",
      translation: "yoga",
      original: "yoga",
      category: "ćwiczenia",
    },
    { word: "zoo", translation: "zoo", original: "zoo", category: "miejsca" },
    {
      word: "amour",
      translation: "miłość",
      original: "amour",
      category: "emocje",
    },
    {
      word: "baguette",
      translation: "bagietka",
      original: "baguette",
      category: "jedzenie",
    },
    {
      word: "cadeau",
      translation: "prezent",
      original: "cadeau",
      category: "przedmiot",
    },
    {
      word: "cafe",
      translation: "kawa",
      original: "café",
      category: "jedzenie",
    },
    {
      word: "dent",
      translation: "ząb",
      original: "dent",
      category: "człowiek",
    },
    { word: "eau", translation: "woda", original: "eau", category: "natura" },
    {
      word: "feuille",
      translation: "liść",
      original: "feuille",
      category: "natura",
    },
    {
      word: "girafe",
      translation: "żyrafa",
      original: "girafe",
      category: "zwierzęta",
    },
    {
      word: "heureux",
      translation: "szczęśliwy",
      original: "heureux",
      category: "emocje",
    },
    {
      word: "ile",
      translation: "wyspa",
      original: "île",
      category: "geografia",
    },
    {
      word: "jouet",
      translation: "zabawka",
      original: "jouet",
      category: "przedmiot",
    },
  ],
  german: [
    {
      word: "apfel",
      translation: "jabłko",
      original: "Apfel",
      category: "jedzenie",
    },
    {
      word: "bier",
      translation: "piwo",
      original: "Bier",
      category: "napój",
    },
    {
      word: "computer",
      translation: "komputer",
      original: "Computer",
      category: "technologia",
    },
    {
      word: "danke",
      translation: "dziękuje",
      original: "Danke",
      category: "ekspresja",
    },
    {
      word: "essen",
      translation: "jedzenie",
      original: "Essen",
      category: "jedzenie",
    },
    {
      word: "fruhling",
      translation: "wiosna",
      original: "Frühling",
      category: "natura",
    },
    {
      word: "garten",
      translation: "ogród",
      original: "Garten",
      category: "natura",
    },
    {
      word: "haus",
      translation: "dom",
      original: "Haus",
      category: "budynek",
    },
    {
      word: "igel",
      translation: "jeż",
      original: "Igel",
      category: "zwierzęta",
    },
    {
      word: "jacke",
      translation: "kurtka",
      original: "Jacke",
      category: "ubrania",
    },
    {
      word: "kuchen",
      translation: "ciasto",
      original: "Kuchen",
      category: "jedzenie",
    },
    {
      word: "laptop",
      translation: "laptop",
      original: "Laptop",
      category: "technologia",
    },
    {
      word: "mutter",
      translation: "mama",
      original: "Mutter",
      category: "rodzina",
    },
    {
      word: "nacht",
      translation: "noc",
      original: "Nacht",
      category: "czas",
    },
    {
      word: "orange",
      translation: "pomarańcza",
      original: "Orange",
      category: "jedzenie",
    },
    {
      word: "papier",
      translation: "papier",
      original: "Papier",
      category: "biuro",
    },
    {
      word: "qualitat",
      translation: "jakość",
      original: "Qualität",
      category: "Atrybut",
    },
    {
      word: "regen",
      translation: "deszcz",
      original: "Regen",
      category: "pogoda",
    },
    {
      word: "schule",
      translation: "szkoła",
      original: "Schule",
      category: "budynek",
    },
    {
      word: "tee",
      translation: "herbata",
      original: "Tee",
      category: "napój",
    },
    {
      word: "uhr",
      translation: "zegarek",
      original: "Uhr",
      category: "przedmiot",
    },
    {
      word: "vater",
      translation: "tata",
      original: "Vater",
      category: "rodzina",
    },
    {
      word: "wasser",
      translation: "woda",
      original: "Wasser",
      category: "napój",
    },
    {
      word: "yacht",
      translation: "yacht",
      original: "Yacht",
      category: "pojazd",
    },
    {
      word: "zimmer",
      translation: "pokój",
      original: "Zimmer",
      category: "dom",
    },
    {
      word: "apfelbaum",
      translation: "jabłoń",
      original: "Apfelbaum",
      category: "natura",
    },
    {
      word: "blume",
      translation: "kwiatek",
      original: "Blume",
      category: "natura",
    },
    {
      word: "couch",
      translation: "kanapa",
      original: "Couch",
      category: "dom",
    },
    {
      word: "dankbar",
      translation: "wdzięczny",
      original: "Dankbar",
      category: "emocje",
    },
    {
      word: "eis",
      translation: "lody",
      original: "Eis",
      category: "jedzenie",
    },
    {
      word: "fahrrad",
      translation: "rower",
      original: "Fahrrad",
      category: "pojazd",
    },
    {
      word: "grun",
      translation: "zielony",
      original: "Grün",
      category: "kolor",
    },
    {
      word: "hande",
      translation: "ręce",
      original: "Hände",
      category: "człowiek",
    },
    {
      word: "igel",
      translation: "jeż",
      original: "Igel",
      category: "zwierze",
    },
    { word: "jahr", translation: "rok", original: "Jahr", category: "czas" },
    {
      word: "kamera",
      translation: "kamera",
      original: "Kamera",
      category: "technologia",
    },
    { word: "lampe", translation: "lampa", original: "Lampe", category: "dom" },
    {
      word: "milch",
      translation: "mleko",
      original: "Milch",
      category: "napój",
    },
    {
      word: "nase",
      translation: "nos",
      original: "Nase",
      category: "człowiek",
    },
    {
      word: "osterreich",
      translation: "Austria",
      original: "Österreich",
      category: "kraj",
    },
    {
      word: "pilz",
      translation: "grzyb",
      original: "Pilz",
      category: "jedzenie",
    },
    {
      word: "qualle",
      translation: "Meduza",
      original: "Qualle",
      category: "zwierzęta",
    },
    {
      word: "regenschirm",
      translation: "parasol",
      original: "Regenschirm",
      category: "pogoda",
    },
    {
      word: "schokolade",
      translation: "czekolada",
      original: "Schokolade",
      category: "jedzenie",
    },
    {
      word: "teebeutel",
      translation: "herbata",
      original: "Teebeutel",
      category: "napój",
    },
    {
      word: "violinist",
      translation: "skrzypek",
      original: "Violinist",
      category: "muzyka",
    },
    {
      word: "wald",
      translation: "las",
      original: "Wald",
      category: "natura",
    },
    {
      word: "yogalehrer",
      translation: "nauczyciel yogi",
      original: "Yogalehrer",
      category: "Profesja",
    },
    {
      word: "zoo",
      translation: "zoo",
      original: "Zoo",
      category: "Rozrywka",
    },
    {
      word: "abendessen",
      translation: "obiad",
      original: "Abendessen",
      category: "jedzenie",
    },
    {
      word: "bruder",
      translation: "brat",
      original: "Bruder",
      category: "rodzina",
    },
    {
      word: "chef",
      translation: "szef",
      original: "Chef",
      category: "Profesja",
    },
    {
      word: "diamant",
      translation: "diament",
      original: "Diamant",
      category: "Minerał",
    },
    {
      word: "eier",
      translation: "jajka",
      original: "Eier",
      category: "jedzenie",
    },
    {
      word: "freund",
      translation: "przyjaciel",
      original: "Freund",
      category: "Relacja",
    },
    {
      word: "gitarre",
      translation: "gitara",
      original: "Gitarre",
      category: "Muzyka",
    },
    {
      word: "himmel",
      translation: "niebo",
      original: "Himmel",
      category: "natura",
    },
    {
      word: "insel",
      translation: "wyspa",
      original: "Insel",
      category: "Geografia",
    },
    {
      word: "junge",
      translation: "chłopiec",
      original: "Junge",
      category: "osoba",
    },
    {
      word: "kugelschreiber",
      translation: "długopis",
      original: "Kugelschreiber",
      category: "Przybory szkolne",
    },
    {
      word: "lehrer",
      translation: "nauczyciel",
      original: "Lehrer",
      category: "Profesja",
    },
    {
      word: "maus",
      translation: "mysz",
      original: "Maus",
      category: "zwierzęta",
    },
    {
      word: "nachtisch",
      translation: "deser",
      original: "Nachtisch",
      category: "Jedzenie",
    },
  ],
};

export default words;
