interface Words {
  [key: string]: {
    word: string;
    translation: string;
    original: string;
    category: string;
  }[];
}

const words: Words = {
  english: [
    {
      word: "chair",
      translation: "chair",
      original: "chair",
      category: "Furniture",
    },
    {
      word: "computer",
      translation: "computer",
      original: "computer",
      category: "Technology",
    },
    {
      word: "guitar",
      translation: "guitar",
      original: "guitar",
      category: "Musical Instrument",
    },
    {
      word: "television",
      translation: "television",
      original: "television",
      category: "Electronics",
    },
    {
      word: "book",
      translation: "book",
      original: "book",
      category: "Literature",
    },
    {
      word: "pencil",
      translation: "pencil",
      original: "pencil",
      category: "Stationery",
    },
    {
      word: "shoe",
      translation: "shoe",
      original: "shoe",
      category: "Clothing",
    },
    {
      word: "coffee",
      translation: "coffee",
      original: "coffee",
      category: "Beverage",
    },
    {
      word: "pizza",
      translation: "pizza",
      original: "pizza",
      category: "Food",
    },
    {
      word: "house",
      translation: "house",
      original: "house",
      category: "Architecture",
    },
    {
      word: "ocean",
      translation: "ocean",
      original: "ocean",
      category: "Geography",
    },
    {
      word: "violin",
      translation: "violin",
      original: "violin",
      category: "Musical Instrument",
    },
    {
      word: "airplane",
      translation: "airplane",
      original: "airplane",
      category: "Transportation",
    },
    {
      word: "chocolate",
      translation: "chocolate",
      original: "chocolate",
      category: "Food",
    },
    {
      word: "camera",
      translation: "camera",
      original: "camera",
      category: "Photography",
    },
    {
      word: "telephone",
      translation: "telephone",
      original: "telephone",
      category: "Electronics",
    },
    {
      word: "umbrella",
      translation: "umbrella",
      original: "umbrella",
      category: "Weather",
    },
    {
      word: "soccer",
      translation: "soccer",
      original: "soccer",
      category: "Sports",
    },
    {
      word: "mirror",
      translation: "mirror",
      original: "mirror",
      category: "Furniture",
    },
    {
      word: "diamond",
      translation: "diamond",
      original: "diamond",
      category: "Jewelry",
    },
    {
      word: "toilet",
      translation: "toilet",
      original: "toilet",
      category: "Bathroom",
    },
    {
      word: "sweater",
      translation: "sweater",
      original: "sweater",
      category: "Clothing",
    },
    {
      word: "skyscraper",
      translation: "skyscraper",
      original: "skyscraper",
      category: "Architecture",
    },
    {
      word: "waterfall",
      translation: "waterfall",
      original: "waterfall",
      category: "Nature",
    },
    {
      word: "banana",
      translation: "banana",
      original: "banana",
      category: "Fruit",
    },
    {
      word: "piano",
      translation: "piano",
      original: "piano",
      category: "Musical Instrument",
    },
    {
      word: "fireplace",
      translation: "fireplace",
      original: "fireplace",
      category: "Home",
    },
    {
      word: "jacket",
      translation: "jacket",
      original: "jacket",
      category: "Clothing",
    },
    {
      word: "pepper",
      translation: "pepper",
      original: "pepper",
      category: "Food",
    },
    {
      word: "skateboard",
      translation: "skateboard",
      original: "skateboard",
      category: "Sports",
    },
    {
      word: "elephant",
      translation: "elefante",
      original: "एलिफैंट",
      category: "Animals",
    },
    {
      word: "laptop",
      translation: "laptop",
      original: "laptop",
      category: "Technology",
    },
    {
      word: "gymnastics",
      translation: "gimnasia",
      original: "gymnastics",
      category: "Sports",
    },
    {
      word: "cactus",
      translation: "cactus",
      original: "cactus",
      category: "Plants",
    },
    {
      word: "magazine",
      translation: "revista",
      original: "magazine",
      category: "Literature",
    },
    {
      word: "snowflake",
      translation: "copo de nieve",
      original: "snowflake",
      category: "Weather",
    },
    {
      word: "giraffe",
      translation: "jirafa",
      original: "giraffe",
      category: "Animals",
    },
    {
      word: "motorcycle",
      translation: "motocicleta",
      original: "motorcycle",
      category: "Transportation",
    },
    {
      word: "towel",
      translation: "toalla",
      original: "towel",
      category: "Bathroom",
    },
    {
      word: "sunglasses",
      translation: "gafas de sol",
      original: "sunglasses",
      category: "Fashion",
    },
    { word: "yoga", translation: "yoga", original: "yoga", category: "Sports" },
    {
      word: "penguin",
      translation: "pingüino",
      original: "penguin",
      category: "Animals",
    },
    {
      word: "popcorn",
      translation: "palomitas de maíz",
      original: "popcorn",
      category: "Food",
    },
    {
      word: "mountain",
      translation: "montaña",
      original: "mountain",
      category: "Geography",
    },
    {
      word: "basketball",
      translation: "baloncesto",
      original: "basketball",
      category: "Sports",
    },
    {
      word: "butterfly",
      translation: "mariposa",
      original: "butterfly",
      category: "Animals",
    },
    {
      word: "suitcase",
      translation: "maleta",
      original: "suitcase",
      category: "Travel",
    },
    {
      word: "watermelon",
      translation: "sandía",
      original: "watermelon",
      category: "Fruit",
    },
    {
      word: "violin",
      translation: "violín",
      original: "violin",
      category: "Musical Instrument",
    },
    {
      word: "candle",
      translation: "vela",
      original: "candle",
      category: "Home",
    },
  ],
  spanish: [
    {
      word: "sillon",
      translation: "armchair",
      original: "sillón",
      category: "Furniture",
    },
    {
      word: "naranja",
      translation: "orange",
      original: "naranja",
      category: "Food",
    },
    {
      word: "manzana",
      translation: "apple",
      original: "manzana",
      category: "Food",
    },
    {
      word: "guitarra",
      translation: "guitar",
      original: "guitarra",
      category: "Music",
    },
    {
      word: "telefono",
      translation: "phone",
      original: "teléfono",
      category: "Technology",
    },
    {
      word: "mapa",
      translation: "map",
      original: "mapa",
      category: "Travel",
    },
    {
      word: "bicicleta",
      translation: "bicycle",
      original: "bicicleta",
      category: "Transportation",
    },
    {
      word: "televisor",
      translation: "television",
      original: "televisor",
      category: "Technology",
    },
    {
      word: "musica",
      translation: "music",
      original: "música",
      category: "Music",
    },
    {
      word: "plato",
      translation: "plate",
      original: "plato",
      category: "Food",
    },
    {
      word: "hotel",
      translation: "hotel",
      original: "hotel",
      category: "Travel",
    },
    {
      word: "delfin",
      translation: "dolphin",
      original: "delfín",
      category: "Animals",
    },
    {
      word: "gato",
      translation: "cat",
      original: "gato",
      category: "Animals",
    },
    {
      word: "restaurante",
      translation: "restaurant",
      original: "restaurante",
      category: "Food",
    },
    {
      word: "internet",
      translation: "internet",
      original: "internet",
      category: "Technology",
    },
    {
      word: "chocolate",
      translation: "chocolate",
      original: "chocolate",
      category: "Food",
    },
    {
      word: "silla",
      translation: "chair",
      original: "silla",
      category: "Furniture",
    },
    {
      word: "avion",
      translation: "airplane",
      original: "avión",
      category: "Transportation",
    },
    {
      word: "teclado",
      translation: "keyboard",
      original: "teclado",
      category: "Technology",
    },
    {
      word: "tomate",
      translation: "tomato",
      original: "tomate",
      category: "Food",
    },
    {
      word: "camara",
      translation: "camera",
      original: "cámara",
      category: "Technology",
    },
    {
      word: "juego",
      translation: "game",
      original: "juego",
      category: "Entertainment",
    },
    {
      word: "reloj",
      translation: "watch",
      original: "reloj",
      category: "Fashion",
    },
    {
      word: "teatro",
      translation: "theater",
      original: "teatro",
      category: "Entertainment",
    },
    {
      word: "maleta",
      translation: "suitcase",
      original: "maleta",
      category: "Travel",
    },
    {
      word: "botella",
      translation: "bottle",
      original: "botella",
      category: "Household Items",
    },
    {
      word: "piano",
      translation: "piano",
      original: "piano",
      category: "Musical Instruments",
    },
    {
      word: "videojuego",
      translation: "video game",
      original: "videojuego",
      category: "Entertainment",
    },
    {
      word: "mesa",
      translation: "table",
      original: "mesa",
      category: "Furniture",
    },
    {
      word: "paraguas",
      translation: "umbrella",
      original: "paraguas",
      category: "Accessories",
    },
    {
      word: "estacionamiento",
      translation: "parking lot",
      original: "estacionamiento",
      category: "Transportation",
    },
    {
      word: "lapiz",
      translation: "pencil",
      original: "lápiz",
      category: "Stationery",
    },
    {
      word: "basura",
      translation: "garbage",
      original: "basura",
      category: "Household Items",
    },
    {
      word: "ropa",
      translation: "clothes",
      original: "ropa",
      category: "Clothing",
    },
    {
      word: "ciudad",
      translation: "city",
      original: "ciudad",
      category: "Places",
    },
    {
      word: "cancion",
      translation: "song",
      original: "canción",
      category: "Entertainment",
    },
    {
      word: "adios",
      translation: "goodbye",
      original: "adiós",
      category: "Greeting",
    },
    {
      word: "aguila",
      translation: "eagle",
      original: "águila",
      category: "Animals",
    },
    {
      word: "amigo",
      translation: "friend",
      original: "amigo",
      category: "People",
    },
    {
      word: "bano",
      translation: "bathroom",
      original: "baño",
      category: "Household Items",
    },
    {
      word: "bravo",
      translation: "brave",
      original: "bravo",
      category: "Emotions",
    },
    {
      word: "casa",
      translation: "house",
      original: "casa",
      category: "Places",
    },
    {
      word: "cerveza",
      translation: "beer",
      original: "cerveza",
      category: "Food & Drink",
    },
    { word: "dia", translation: "day", original: "día", category: "Time" },
    {
      word: "elegante",
      translation: "elegant",
      original: "elegante",
      category: "Appearance",
    },
    {
      word: "familia",
      translation: "family",
      original: "familia",
      category: "People",
    },
    {
      word: "guitarra",
      translation: "guitar",
      original: "guitarra",
      category: "Musical Instruments",
    },
    {
      word: "hola",
      translation: "hello",
      original: "hola",
      category: "Greeting",
    },
    {
      word: "iglesia",
      translation: "church",
      original: "iglesia",
      category: "Places",
    },
    {
      word: "jamon",
      translation: "ham",
      original: "jamón",
      category: "Food & Drink",
    },
    {
      word: "jardin",
      translation: "garden",
      original: "jardín",
      category: "Places",
    },
    {
      word: "kiwi",
      translation: "kiwi",
      original: "kiwi",
      category: "Food & Drink",
    },
    {
      word: "lapiz",
      translation: "pencil",
      original: "lápiz",
      category: "school supplies",
    },
    {
      word: "manana",
      translation: "tomorrow",
      original: "mañana",
      category: "time",
    },
    {
      word: "nacion",
      translation: "nation",
      original: "nación",
      category: "politics",
    },
    {
      word: "nono",
      translation: "whiny",
      original: "ñoño",
      category: "slang",
    },
    {
      word: "oido",
      translation: "ear",
      original: "oído",
      category: "anatomy",
    },
    {
      word: "paella",
      translation: "paella",
      original: "paella",
      category: "food",
    },
    {
      word: "queso",
      translation: "cheese",
      original: "queso",
      category: "food",
    },
    {
      word: "rosa",
      translation: "rose",
      original: "rosa",
      category: "plants",
    },
    {
      word: "silla",
      translation: "chair",
      original: "silla",
      category: "furniture",
    },
    {
      word: "taco",
      translation: "taco",
      original: "taco",
      category: "food",
    },
    {
      word: "uva",
      translation: "grape",
      original: "uva",
      category: "food",
    },
    {
      word: "vacaciones",
      translation: "vacation",
      original: "vacaciones",
      category: "travel",
    },
    {
      word: "wok",
      translation: "wok",
      original: "wok",
      category: "cookware",
    },
    {
      word: "yoga",
      translation: "yoga",
      original: "yoga",
      category: "exercise",
    },
    {
      word: "zapato",
      translation: "shoe",
      original: "zapato",
      category: "clothing",
    },
    {
      word: "arbol",
      translation: "tree",
      original: "árbol",
      category: "plants",
    },
    {
      word: "exito",
      translation: "success",
      original: "éxito",
      category: "motivation",
    },
  ],
  polish: [
    {
      word: "samolot",
      translation: "airplane",
      original: "samolot",
      category: "transportation",
    },
    {
      word: "milosc",
      translation: "love",
      original: "miłość",
      category: "emotions",
    },
    {
      word: "zolw",
      translation: "turtle",
      original: "żółw",
      category: "animals",
    },
    {
      word: "kot",
      translation: "cat",
      original: "kot",
      category: "animals",
    },
    {
      word: "pies",
      translation: "dog",
      original: "pies",
      category: "animals",
    },
    {
      word: "ksiazka",
      translation: "book",
      original: "książka",
      category: "education",
    },
    {
      word: "witaj",
      translation: "hello",
      original: "witaj",
      category: "greetings",
    },
    {
      word: "do widzenia",
      translation: "goodbye",
      original: "do widzenia",
      category: "greetings",
    },
    {
      word: "dom",
      translation: "house",
      original: "dom",
      category: "housing",
    },
    {
      word: "gra",
      translation: "game",
      original: "gra",
      category: "entertainment",
    },
    {
      word: "jedzenie",
      translation: "food",
      original: "jedzenie",
      category: "food",
    },
    {
      word: "woda",
      translation: "water",
      original: "woda",
      category: "drinks",
    },
    {
      word: "szkoda",
      translation: "pity",
      original: "szkoda",
      category: "emotions",
    },
    {
      word: "kawa",
      translation: "coffee",
      original: "kawa",
      category: "drinks",
    },
    {
      word: "herbata",
      translation: "tea",
      original: "herbata",
      category: "drinks",
    },
    {
      word: "aniol",
      translation: "angel",
      original: "anioł",
      category: "religion",
    },
    {
      word: "babcia",
      translation: "grandmother",
      original: "babcia",
      category: "family",
    },
    {
      word: "czekolada",
      translation: "chocolate",
      original: "czekolada",
      category: "food",
    },
    {
      word: "domek",
      translation: "house",
      original: "domek",
      category: "housing",
    },
    {
      word: "ekran",
      translation: "screen",
      original: "ekran",
      category: "technology",
    },
    {
      word: "filizanka",
      translation: "cup",
      original: "filiżanka",
      category: "kitchenware",
    },
    {
      word: "grzyb",
      translation: "mushroom",
      original: "grzyb",
      category: "food",
    },
    {
      word: "hazard",
      translation: "gambling",
      original: "hazard",
      category: "entertainment",
    },
    {
      word: "igla",
      translation: "needle",
      original: "igła",
      category: "sewing",
    },
    {
      word: "jablko",
      translation: "apple",
      original: "jabłko",
      category: "food",
    },
    {
      word: "kawa",
      translation: "coffee",
      original: "kawa",
      category: "drink",
    },
    {
      word: "lampa",
      translation: "lamp",
      original: "lampa",
      category: "household",
    },
    {
      word: "marchew",
      translation: "carrot",
      original: "marchew",
      category: "food",
    },
    {
      word: "niedziela",
      translation: "Sunday",
      original: "niedziela",
      category: "time",
    },
    {
      word: "obraz",
      translation: "picture",
      original: "obraz",
      category: "art",
    },
    {
      word: "pajak",
      translation: "spider",
      original: "pająk",
      category: "animal",
    },
    { word: "reka", translation: "hand", original: "ręka", category: "body" },
    {
      word: "serce",
      translation: "heart",
      original: "serce",
      category: "body",
    },
    {
      word: "torebka",
      translation: "bag",
      original: "torebka",
      category: "accessory",
    },
    { word: "ucho", translation: "ear", original: "ucho", category: "body" },
    { word: "woda", translation: "water", original: "woda", category: "drink" },
    {
      word: "yacht",
      translation: "yacht",
      original: "jacht",
      category: "vehicle",
    },
    {
      word: "zamek",
      translation: "castle/lock",
      original: "zamek",
      category: "place/object",
    },
  ],
  french: [
    {
      word: "bonjour",
      translation: "hello",
      original: "bonjour",
      category: "greetings",
    },
    {
      word: "chateau",
      translation: "castle",
      original: "château",
      category: "places",
    },
    {
      word: "delicieux",
      translation: "delicious",
      original: "délicieux",
      category: "food",
    },
    {
      word: "ecole",
      translation: "school",
      original: "école",
      category: "education",
    },
    {
      word: "fleur",
      translation: "flower",
      original: "fleur",
      category: "nature",
    },
    {
      word: "gateau",
      translation: "cake",
      original: "gâteau",
      category: "food",
    },
    {
      word: "heureux",
      translation: "happy",
      original: "heureux",
      category: "emotions",
    },
    {
      word: "invitation",
      translation: "invitation",
      original: "invitation",
      category: "events",
    },
    {
      word: "jardin",
      translation: "garden",
      original: "jardin",
      category: "nature",
    },
    { word: "kiwi", translation: "kiwi", original: "kiwi", category: "food" },
    {
      word: "lingerie",
      translation: "lingerie",
      original: "lingerie",
      category: "clothing",
    },
    {
      word: "musique",
      translation: "music",
      original: "musique",
      category: "entertainment",
    },
    {
      word: "noir",
      translation: "black",
      original: "noir",
      category: "colors",
    },
    {
      word: "oiseau",
      translation: "bird",
      original: "oiseau",
      category: "animals",
    },
    {
      word: "parfum",
      translation: "perfume",
      original: "parfum",
      category: "beauty",
    },
    {
      word: "quatre",
      translation: "four",
      original: "quatre",
      category: "numbers",
    },
    {
      word: "restaurant",
      translation: "restaurant",
      original: "restaurant",
      category: "food",
    },
    {
      word: "sourire",
      translation: "smile",
      original: "sourire",
      category: "emotions",
    },
    {
      word: "tableau",
      translation: "painting",
      original: "tableau",
      category: "art",
    },
    {
      word: "unique",
      translation: "unique",
      original: "unique",
      category: "qualities",
    },
    {
      word: "vache",
      translation: "cow",
      original: "vache",
      category: "animals",
    },
    {
      word: "wagon",
      translation: "wagon",
      original: "wagon",
      category: "vehicles",
    },
    {
      word: "yoga",
      translation: "yoga",
      original: "yoga",
      category: "exercise",
    },
    { word: "zoo", translation: "zoo", original: "zoo", category: "places" },
    {
      word: "amour",
      translation: "love",
      original: "amour",
      category: "emotions",
    },
    {
      word: "baguette",
      translation: "baguette",
      original: "baguette",
      category: "food",
    },
    {
      word: "cadeau",
      translation: "gift",
      original: "cadeau",
      category: "events",
    },
    { word: "cafe", translation: "coffee", original: "café", category: "food" },
    {
      word: "dent",
      translation: "tooth",
      original: "dent",
      category: "body parts",
    },
    { word: "eau", translation: "water", original: "eau", category: "nature" },
    {
      word: "feuille",
      translation: "leaf",
      original: "feuille",
      category: "nature",
    },
    {
      word: "girafe",
      translation: "giraffe",
      original: "girafe",
      category: "animals",
    },
    {
      word: "heureux",
      translation: "happy",
      original: "heureux",
      category: "emotions",
    },
    {
      word: "ile",
      translation: "island",
      original: "île",
      category: "geography",
    },
    { word: "jouet", translation: "toy", original: "jouet", category: "toys" },
  ],
  german: [
    {
      word: "apfel",
      translation: "apple",
      original: "Apfel",
      category: "Food",
    },
    {
      word: "bier",
      translation: "beer",
      original: "Bier",
      category: "Beverage",
    },
    {
      word: "computer",
      translation: "computer",
      original: "Computer",
      category: "Technology",
    },
    {
      word: "danke",
      translation: "thank you",
      original: "Danke",
      category: "Expression",
    },
    {
      word: "essen",
      translation: "food",
      original: "Essen",
      category: "Food",
    },
    {
      word: "fruhling",
      translation: "spring",
      original: "Frühling",
      category: "Season",
    },
    {
      word: "garten",
      translation: "garden",
      original: "Garten",
      category: "Nature",
    },
    {
      word: "haus",
      translation: "house",
      original: "Haus",
      category: "Housing",
    },
    {
      word: "igel",
      translation: "hedgehog",
      original: "Igel",
      category: "Nature",
    },
    {
      word: "jacke",
      translation: "jacket",
      original: "Jacke",
      category: "Clothing",
    },
    {
      word: "kuchen",
      translation: "cake",
      original: "Kuchen",
      category: "Food",
    },
    {
      word: "laptop",
      translation: "laptop",
      original: "Laptop",
      category: "Technology",
    },
    {
      word: "mutter",
      translation: "mother",
      original: "Mutter",
      category: "Family",
    },
    {
      word: "nacht",
      translation: "night",
      original: "Nacht",
      category: "Time",
    },
    {
      word: "orange",
      translation: "orange",
      original: "Orange",
      category: "Food",
    },
    {
      word: "papier",
      translation: "paper",
      original: "Papier",
      category: "Office",
    },
    {
      word: "qualitat",
      translation: "quality",
      original: "Qualität",
      category: "Attribute",
    },
    {
      word: "regen",
      translation: "rain",
      original: "Regen",
      category: "Weather",
    },
    {
      word: "schule",
      translation: "school",
      original: "Schule",
      category: "Education",
    },
    {
      word: "tee",
      translation: "tea",
      original: "Tee",
      category: "Beverage",
    },
    { word: "uhr", translation: "clock", original: "Uhr", category: "time" },
    {
      word: "vater",
      translation: "father",
      original: "Vater",
      category: "family",
    },
    {
      word: "wasser",
      translation: "water",
      original: "Wasser",
      category: "food/drink",
    },
    {
      word: "xylophon",
      translation: "xylophone",
      original: "Xylophon",
      category: "music",
    },
    {
      word: "yacht",
      translation: "yacht",
      original: "Yacht",
      category: "travel",
    },
    {
      word: "zimmer",
      translation: "room",
      original: "Zimmer",
      category: "home",
    },
    {
      word: "apfelbaum",
      translation: "apple tree",
      original: "Apfelbaum",
      category: "nature",
    },
    {
      word: "blume",
      translation: "flower",
      original: "Blume",
      category: "nature",
    },
    {
      word: "couch",
      translation: "couch",
      original: "Couch",
      category: "home",
    },
    {
      word: "dankbar",
      translation: "grateful",
      original: "Dankbar",
      category: "emotions",
    },
    {
      word: "eis",
      translation: "ice cream",
      original: "Eis",
      category: "food/drink",
    },
    {
      word: "fahrrad",
      translation: "bicycle",
      original: "Fahrrad",
      category: "transportation",
    },
    { word: "grun", translation: "green", original: "Grün", category: "color" },
    {
      word: "hande",
      translation: "hands",
      original: "Hände",
      category: "body parts",
    },
    {
      word: "igel",
      translation: "hedgehog",
      original: "Igel",
      category: "animals",
    },
    { word: "jahr", translation: "year", original: "Jahr", category: "time" },
    {
      word: "kamera",
      translation: "camera",
      original: "Kamera",
      category: "technology",
    },
    { word: "lampe", translation: "lamp", original: "Lampe", category: "home" },
    {
      word: "milch",
      translation: "milk",
      original: "Milch",
      category: "food/drink",
    },
    {
      word: "nase",
      translation: "nose",
      original: "Nase",
      category: "body parts",
    },
    {
      word: "osterreich",
      translation: "Austria",
      original: "Österreich",
      category: "geography",
    },
    {
      word: "pilz",
      translation: "mushroom",
      original: "Pilz",
      category: "food/drink",
    },
    {
      word: "qualle",
      translation: "jellyfish",
      original: "Qualle",
      category: "animals",
    },
    {
      word: "regenschirm",
      translation: "umbrella",
      original: "Regenschirm",
      category: "weather",
    },
    {
      word: "schokolade",
      translation: "chocolate",
      original: "Schokolade",
      category: "food/drink",
    },
    {
      word: "teebeutel",
      translation: "tea bag",
      original: "Teebeutel",
      category: "food/drink",
    },
    {
      word: "uber",
      translation: "over",
      original: "Über",
      category: "language",
    },
    {
      word: "violinist",
      translation: "violinist",
      original: "Violinist",
      category: "music",
    },
    {
      word: "wald",
      translation: "forest",
      original: "Wald",
      category: "Nature",
    },
    {
      word: "yogalehrer",
      translation: "yoga teacher",
      original: "Yogalehrer",
      category: "Profession",
    },
    {
      word: "zoo",
      translation: "zoo",
      original: "Zoo",
      category: "Entertainment",
    },
    {
      word: "abendessen",
      translation: "dinner",
      original: "Abendessen",
      category: "Food",
    },
    {
      word: "bruder",
      translation: "brother",
      original: "Bruder",
      category: "Family",
    },
    {
      word: "chef",
      translation: "chef",
      original: "Chef",
      category: "Profession",
    },
    {
      word: "diamant",
      translation: "diamond",
      original: "Diamant",
      category: "Mineral",
    },
    { word: "eier", translation: "eggs", original: "Eier", category: "Food" },
    {
      word: "freund",
      translation: "friend",
      original: "Freund",
      category: "Relationship",
    },
    {
      word: "gitarre",
      translation: "guitar",
      original: "Gitarre",
      category: "Music",
    },
    {
      word: "himmel",
      translation: "sky",
      original: "Himmel",
      category: "Nature",
    },
    {
      word: "insel",
      translation: "island",
      original: "Insel",
      category: "Geography",
    },
    {
      word: "junge",
      translation: "boy",
      original: "Junge",
      category: "Person",
    },
    {
      word: "kugelschreiber",
      translation: "pen",
      original: "Kugelschreiber",
      category: "Stationery",
    },
    {
      word: "lehrer",
      translation: "teacher",
      original: "Lehrer",
      category: "Profession",
    },
    {
      word: "maus",
      translation: "mouse",
      original: "Maus",
      category: "Animal",
    },
    {
      word: "nachtisch",
      translation: "dessert",
      original: "Nachtisch",
      category: "Food",
    },
  ],
};

export default words;
